server:
  port: 8080

spring:
  datasource:
    username: usr
    password: pwd
    url: jdbc:postgresql://localhost:5430/demoDB
  jpa:
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

indexing-settings:
  sites:
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.playback.ru
      name: PlayBack.Ru
    - url: https://ria.ru
      name: РИА новости

connection-settings:
  userAgent: Mozilla/5.0 (X11; Fedora;Linux x86; rv:60.0) Gecko/20100101 Firefox/60.0
  referer: https://www.google.com